### ISSUE TITLE
WordCounter for "Anna-Maria" returns 3

### ISSUE THREAD

**Issue by daberlin** [heiglandreas/TextStatistics#2]
The WordCounter produces unexpected results...

require __DIR__ . '/vendor/autoload.php';
use \Org_Heigl\TextStatistics as Ts;
$tsg = new Ts\TextStatisticsGenerator();
$tsg->add('word_count', Ts\Service\WordCounterFactory::getCalculator());
print_r($tsg->calculate(new Ts\Text("Anna-Maria")));

... returns a [word_count] => 3, but I'd expect 2.

**Comment by heiglandreas** [comment]
Thanks for noticing! I'm digging into it!

**Comment by heiglandreas** [comment]
You will need to call ```composer update org_heigl/hyphenator``` to fix this issue.

The reason was an error in the tokenizer of the hyphenator-library that was fixed with https://github.com/heiglandreas/Org_Heigl_Hyphenator/releases/tag/v2.0.6

**Comment by heiglandreas** [comment]
BTW: There's now a test that checks for Anna-Maria: https://github.com/heiglandreas/TextStatistics/blob/0.1.0/tests/Calculator/WordCounterTest.php#L54

**Comment by daberlin** [comment]
Super - Problem gelöst!
Besten Dank

Mit freundlichem Gruß,
Daniel Berlin
