### ISSUE TITLE
More languages

### ISSUE THREAD

**Issue by manocarayannis** [heiglandreas/TextStatistics#7]
How can I add more languages to this? I'm interested for Greek in particular.

Thank you for your great git.

**Comment by heiglandreas** [comment]
How do you mean? Most of the statistics should work for greek as they work for any other language. Like Char-Counter etc. 

The syllables-counter and all statistics that require syllables should be able to handle greek as well, as soon as there's a greek hyphenation dictionary for https://github.com/heiglandreas/Org_Heigl_Hyphenator available…

Do you know of a TeX-hyphenation dictionary for greek?

**Comment by heiglandreas** [comment]
I've just found a greek hyphenation dictionary and added that to the Hyphenator. So after a `composer update` the text-statistics should also work for `el_GR`-locale ;)

**Comment by manocarayannis** [comment]
Thank you very very... very much!

**Comment by heiglandreas** [comment]
Did it work? ;-)

**Comment by manocarayannis** [comment]
Yes, it does! No issues so far, thanks again!
